# Generated by Django 2.2.7 on 2019-12-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('working_hours', models.TimeField()),
                ('date_join', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True, verbose_name='Left Date')),
                ('status', models.BooleanField(verbose_name='Employee Active Status')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('working_hours', models.TimeField()),
                ('date_join', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('history_change_reason', models.CharField(max_length=50)),
                ('history_type', models.CharField(max_length=10)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'db_table': 'employee_audit_trail',
            },
        ),
    ]
