# Generated by Django 2.2.6 on 2019-11-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191112_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAuditTrail',
        ),
    ]
