# Generated by Django 2.2.7 on 2019-11-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_historicalemployee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalemployee',
            table='employee_audit_trail',
        ),
    ]
